### ISSUE TITLE
ezshare@1.11.3 don't work 

### ISSUE THREAD

**Issue by Sumit931kr** [mifi/ezshare#111]
![image](https://github.com/user-attachments/assets/851bcf7f-9c43-4514-a069-7f595feb3e9d)
 this error in the browser
 
 and 
 
![image](https://github.com/user-attachments/assets/e529f90e-fc3f-405e-bcea-e1c043eba65a)

 this one is in the console.

**Comment by mifi** [comment]
How did you install ezahare?

**Comment by Sumit931kr** [comment]
npm install -g ezshare@latest

**Comment by mifi** [comment]
thanks. fixed in 1.11.4
