### ISSUE TITLE
files and folder are not shown in version ezshare@1.11.4

### ISSUE THREAD

**Issue by Sumit931kr** [mifi/ezshare#112]
![image](https://github.com/user-attachments/assets/2ec711a0-4fcd-4066-94e4-523587b5b9a8)
this is the console message 

![image](https://github.com/user-attachments/assets/e9012996-1353-4e9b-9ad6-1b2ec61dd059)
and this is in the browser

**Comment by mifi** [comment]
did you write `ezshare .`? try just `ezshare` - i will fix

**Comment by mifi** [comment]
fixed in latest version
