### ISSUE TITLE
Port  8080 is not working due to postgres sql

### ISSUE THREAD

**Issue by gorisab-au7** [mifi/ezshare#15]
Please change the default sharing port to unique port like 5505 or 3001.
I'm unable to use ezshare on my pc due to postgres sql it was running on 8080 by default.
Please consider this, Thank You

**Comment by mifi** [comment]
You can run `ezshare --port 5505`

**Comment by gorisab-au7** [comment]
Thank you for your response, please tell me how to modify port on win.exe
file, its not taking any input,
Or please change the port number to other than 8080

**Comment by mifi** [comment]
Doesn't it work `ezshare.exe --port 5505`?

**Comment by gorisab-au7** [comment]
It's Working, Thank you so much.
But please change the default port 8080 to any random port in win.exe

🙏🙏

**Comment by mifi** [comment]
I think you could make a batch script
