### ISSUE TITLE
Improve name of uploaded file (include parts of original name)

### ISSUE THREAD

**Issue by mifi** [mifi/ezshare#6]

**Comment by dxtr80** [comment]
It will be nice if file will be uploaded to current folder instead of ezshare root folder as well. By the way, very nice software, great to share files in hotel room etc.

**Comment by mifi** [comment]
I think it's not possible for a command line program to detect the current folder of Explorer/Finder without passing it as a command line arg. This could be possible if we made a GUI for ezshare

**Comment by mifi** [comment]
File name preservatiion is implemented
