### ISSUE TITLE
wrong IP address in url

### ISSUE THREAD

**Issue by abyssox** [mifi/ezshare#87]
With the latest version 1.10.0 the displayed ip address in the url (in my case 172.19.0.1) is wrong:
![image](https://github.com/mifi/ezshare/assets/4539953/2c4746f5-2a7d-46e3-a877-6c116e541e77)

Correct ip address should be 172.17.1.74:
![image](https://github.com/mifi/ezshare/assets/4539953/211c4e98-24b0-4a62-a26c-74cd61f1a15e)

**Comment by mifi** [comment]
1. is there is only a single IP address and QR code printed by ezshare?
2. is the behaviour different in v1.9?

**Comment by abyssox** [comment]
> 1. is there is only a single IP address and QR code printed by ezshare?

omg i'm such a fool :/ 
Scrolled up and there is indeed a second QR Code with the correct URL.

Any chance to implement a feature to choose which adapter to use?
